# This is a generated file. Not intended for manual editing.
services:
  userapi:
    build:
      context: "/Users/ming/Desktop/AntraHw/HRMSolution/HRMSolution"
      dockerfile: "UserAPI/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net6.0/UserAPI.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    image: "userapi:dev"
    ports: []
    volumes:
    - "/Users/ming/Desktop/AntraHw/HRMSolution/HRMSolution/UserAPI:/app:rw"
    working_dir: "/app"
