services:
  userapi:
    image: userapi
    build:
      context: .
      dockerfile: UserAPI/Dockerfile
    ports:
      - "40121:80"
  
  recruitingapi:
    image: recruitingapi
    build:
      context: .
      dockerfile: RecruitingAPI/Dockerfile
    ports:
      - "40122:80"

  interviewapi:
    image: interviewapi
    build:
      context: .
      dockerfile: InterviewAPI/Dockerfile
    ports:
      - "40123:80"


