version: '3.4'
services:
  recruitingapi:
    image: recruitingapi
    build:
      context: .
      dockerfile: RecruitingAPI/Dockerfile
  Authenticationapi:
    image: authenticationapi
    build:
      context: .
      dockerfile: UserAPI/Dockerfile
    ports:
      - "40123:80"